version: "3.9"

services:
    db:
      image: mysql:5.7
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=seminario_maraba
      ports:
        - 3306:3306
      volumes:
        - db:/var/lib/mysql

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      links:
        - db
      ports:
        - 8081:80
      environment:
        - PMA_ARBITRARY=1

    php:
      build: ./php-docker
      volumes:
        - .:/webapp
      restart: unless-stopped
      tty: true
      depends_on:
        - db

    nginx:
      image: nginx:latest
      ports:
        - "80:80"
      volumes:
        - .:/webapp
        - ./site.conf:/etc/nginx/conf.d/default.conf
      restart: unless-stopped
      tty: true
      depends_on:
        - php


